services:
  - type: web
    name: resumegptbackend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PORT
        value: 8000
    disk:
      name: uploads
      mountPath: /opt/render/uploads
      sizeGB: 1 